"""feat: add transactions table

Revision ID: 978cf29d1766
Revises: f4e91870f4ef
Create Date: 2026-07-14 07:00:05.176030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '978cf29d1766'
down_revision: Union[str, Sequence[str], None] = 'f4e91870f4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
